### ISSUE TITLE
Would like to see a new tag when fixes are merged

### ISSUE THREAD

**Issue by TheLinuxNinja** [Aigeruth/pure-ftpd#12]
We use automation to pull the cookbook, but best practices are to never pull from an ever-changing master, so that no future change breaks existing systems.

Can we get the current version tagged (esp the Sept. merge that fixes the puredb backend) so we can pull from your upstream instead of pulling from our own fork?

Thanks!

**Comment by Aigeruth** [comment]
I've tagged the current state with `v0.2.1`. If you use [Berkshelf](http://berkshelf.com/), you can also do something like this:

```ruby
cookbook "mysql", git: "https://github.com/opscode-cookbooks/mysql.git", ref: "eef7e65806e7ff3bdbe148e27c447ef4a8bc3881"
```
